source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'voiceCall_rn' do
  # Pods for voiceCall_rn
  pod 'TwilioVoice'
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

  use_native_modules!

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'
  
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'


  pod 'JPushRN', :path => '../node_modules/jpush-react-native'

  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
  
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

#  pod 'RNSyanImagePicker', :path => '../node_modules/react-native-syan-image-picker'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'react-native-video', :path => '../node_modules/react-native-video'
  
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

end
