SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for wold_country
-- ----------------------------
DROP TABLE IF EXISTS `wold_country`;
CREATE TABLE `wold_country` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `country_en` varchar(50) DEFAULT NULL,
  `country_cn` varchar(50) DEFAULT NULL,
  `country_code` char(10) DEFAULT NULL,
  `continent` varchar(50) DEFAULT NULL,
  `country_no` char(10) DEFAULT NULL,
  `status` tinyint(2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=243 DEFAULT CHARSET=utf8 COMMENT="世界国家表";

-- ----------------------------
-- Records of wold_country
-- ----------------------------
INSERT INTO `wold_country` VALUES ("1", "Afghanistan", "阿富汗", "AF", "亚洲", "93", "1");
INSERT INTO `wold_country` VALUES ("2", "Albania", "阿尔巴尼亚", "AL", "欧洲", "355", "1");
INSERT INTO `wold_country` VALUES ("3", "Algeria", "阿尔及利亚", "DZ", "非洲", "213", "1");
INSERT INTO `wold_country` VALUES ("4", "American Samoa", "萨摩亚", "AS", "大洋洲", "684", "1");
INSERT INTO `wold_country` VALUES ("5", "Andorra", "安道尔共和国", "AD", "欧洲", "376", "1");
INSERT INTO `wold_country` VALUES ("6", "Angola", "安哥拉", "AO", "非洲", "244", "1");
INSERT INTO `wold_country` VALUES ("7", "Anguilla", "安圭拉", "AI", "欧洲", "1264", "1");
INSERT INTO `wold_country` VALUES ("8", "Antarctica", "南极洲", "AQ", "", "672", "1");
INSERT INTO `wold_country` VALUES ("9", "Antigua and Barbuda", "安提瓜和巴布达", "AG", "北美洲", "1268", "1");
INSERT INTO `wold_country` VALUES ("10", "Argentina", "阿根廷", "AR", "南美洲", "54", "1");
INSERT INTO `wold_country` VALUES ("11", "Armenia", "亚美尼亚", "AM", "亚洲", "374", "1");
INSERT INTO `wold_country` VALUES ("12", "Aruba", "阿鲁巴", "AW", "北美洲", "297", "1");
INSERT INTO `wold_country` VALUES ("13", "Australia", "澳大利亚", "AU", "大洋洲", "61", "1");
INSERT INTO `wold_country` VALUES ("14", "Austria", "奥地利", "AT", "欧洲", "43", "1");
INSERT INTO `wold_country` VALUES ("15", "Azerbaijan", "阿塞拜疆", "AZ", "亚洲", "994", "1");
INSERT INTO `wold_country` VALUES ("16", "Bahamas", "巴哈马", "BS", "北美洲", "1242", "1");
INSERT INTO `wold_country` VALUES ("17", "Bahrain", "巴林", "BH", "亚洲", "973", "1");
INSERT INTO `wold_country` VALUES ("18", "Bangladesh", "孟加拉国", "BD", "亚洲", "880", "1");
INSERT INTO `wold_country` VALUES ("19", "Barbados", "巴巴多斯", "BB", "北美洲", "1246", "1");
INSERT INTO `wold_country` VALUES ("20", "Belarus", "白俄罗斯", "BY", "欧洲", "375", "1");
INSERT INTO `wold_country` VALUES ("21", "Belgium", "比利时", "BE", "欧洲", "32", "1");
INSERT INTO `wold_country` VALUES ("22", "Belize", "伯利兹城", "BZ", "北美洲", "501", "1");
INSERT INTO `wold_country` VALUES ("23", "Benin", "贝宁", "BJ", "非洲", "229", "1");
INSERT INTO `wold_country` VALUES ("24", "Bermuda", "百慕大", "BM", "欧洲", "1441", "1");
INSERT INTO `wold_country` VALUES ("25", "Bhutan", "不丹", "BT", "亚洲", "975", "1");
INSERT INTO `wold_country` VALUES ("26", "Bolivia", "玻利维亚", "BO", "南美洲", "591", "1");
INSERT INTO `wold_country` VALUES ("27", "Bosnia and Herzegovina", "波斯尼亚和黑塞哥维那", "BA", "欧洲", "387", "1");
INSERT INTO `wold_country` VALUES ("28", "Botswana", "博茨瓦纳", "BW", "非洲", "267", "1");
INSERT INTO `wold_country` VALUES ("29", "Bouvet Island", "布维岛", "BV", "", "", "1");
INSERT INTO `wold_country` VALUES ("30", "Brazil", "巴西", "BR", "南美洲", "55", "1");
INSERT INTO `wold_country` VALUES ("31", "British Indian Ocean Territory", "英属印度洋领地", "IO", "亚洲", "1284", "1");
INSERT INTO `wold_country` VALUES ("32", "Brunei Darussalam", "文莱达鲁萨兰国", "BN", "亚洲", "673", "1");
INSERT INTO `wold_country` VALUES ("33", "Bulgaria", "保加利亚", "BG", "欧洲", "359", "1");
INSERT INTO `wold_country` VALUES ("34", "Burkina Faso", "布基纳法索", "BF", "非洲", "226", "1");
INSERT INTO `wold_country` VALUES ("35", "Burundi", "布隆迪", "BI", "非洲", "257", "1");
INSERT INTO `wold_country` VALUES ("36", "Cambodia", "柬埔寨", "KH", "亚洲", "855", "1");
INSERT INTO `wold_country` VALUES ("37", "Cameroon", "喀麦隆", "CM", "非洲", "237", "1");
INSERT INTO `wold_country` VALUES ("38", "Canada", "加拿大", "CA", "北美洲", "1", "1");
INSERT INTO `wold_country` VALUES ("39", "Cape Verde", "佛得角", "CV", "非洲", "238", "1");
INSERT INTO `wold_country` VALUES ("40", "Cayman Islands", "开曼群岛", "KY", "北美洲", "1345", "1");
INSERT INTO `wold_country` VALUES ("41", "Central African Republic", "中非共和国", "CF", "非洲", "236", "1");
INSERT INTO `wold_country` VALUES ("42", "Chad", "乍得", "TD", "非洲", "235", "1");
INSERT INTO `wold_country` VALUES ("43", "Chile", "智利", "CL", "南美洲", "56", "1");
INSERT INTO `wold_country` VALUES ("44", "China", "中国", "CN", "亚洲", "86", "1");
INSERT INTO `wold_country` VALUES ("45", "Christmas Island", "圣延岛", "CX", "", "61", "1");
INSERT INTO `wold_country` VALUES ("46", "Cocos (Keeling) Islands", "科科斯群岛", "CC", "大洋洲", "61", "1");
INSERT INTO `wold_country` VALUES ("47", "Colombia", "哥伦比亚", "CO", "南美洲", "57", "1");
INSERT INTO `wold_country` VALUES ("48", "Comoros", "科摩罗", "KM", "非洲", "269", "1");
INSERT INTO `wold_country` VALUES ("49", "Congo", "刚果", "CG", "非洲", "242", "1");
INSERT INTO `wold_country` VALUES ("50", "Congo, The Democratic Republic Of The", "刚果民主共和国", "ZR", "非洲", "243", "1");
INSERT INTO `wold_country` VALUES ("51", "Cook Islands", "库克群岛", "CK", "大洋洲", "682", "1");
INSERT INTO `wold_country` VALUES ("52", "Costa Rica", "哥斯达黎加", "CR", "北美洲", "506", "1");
INSERT INTO `wold_country` VALUES ("53", "Cote D'Ivoire", "Cote D'Ivoire", "CI", "", "225", "0");
INSERT INTO `wold_country` VALUES ("54", "Croatia (local name: Hrvatska)", "克罗地亚", "HR", "欧洲", "385", "1");
INSERT INTO `wold_country` VALUES ("55", "Cuba", "古巴", "CU", "北美洲", "53", "1");
INSERT INTO `wold_country` VALUES ("56", "Cyprus", "塞浦路斯", "CY", "亚洲", "357", "1");
INSERT INTO `wold_country` VALUES ("57", "Czech Republic", "捷克", "CZ", "欧洲", "420", "1");
INSERT INTO `wold_country` VALUES ("58", "Denmark", "丹麦", "DK", "欧洲", "45", "1");
INSERT INTO `wold_country` VALUES ("59", "Djibouti", "吉布提", "DJ", "非洲", "253", "1");
INSERT INTO `wold_country` VALUES ("60", "Dominica", "多米尼克国", "DM", "北美洲", "1767", "1");
INSERT INTO `wold_country` VALUES ("61", "Dominican Republic", "多米尼加共和国", "DO", "欧洲", "1809", "1");
INSERT INTO `wold_country` VALUES ("62", "East Timor", "东帝汶", "TP", "亚洲", "670", "1");
INSERT INTO `wold_country` VALUES ("63", "Ecuador", "厄瓜多尔", "EC", "南美洲", "593", "1");
INSERT INTO `wold_country` VALUES ("64", "Egypt", "埃及", "EG", "非洲", "20", "1");
INSERT INTO `wold_country` VALUES ("65", "El Salvador", "萨尔瓦多", "SV", "南美洲", "503", "1");
INSERT INTO `wold_country` VALUES ("66", "Equatorial Guinea", "赤道几内亚", "GQ", "非洲", "240", "1");
INSERT INTO `wold_country` VALUES ("67", "Eritrea", "厄立特里亚国", "ER", "非洲", "291", "1");
INSERT INTO `wold_country` VALUES ("68", "Estonia", "爱沙尼亚", "EE", "欧洲", "372", "1");
INSERT INTO `wold_country` VALUES ("69", "Ethiopia", "埃塞俄比亚", "ET", "非洲", "251", "1");
INSERT INTO `wold_country` VALUES ("70", "Falkland Islands (Malvinas)", "福克兰群岛", "FK", "", "500", "1");
INSERT INTO `wold_country` VALUES ("71", "Faroe Islands", "法罗群岛", "FO", "欧洲", "298", "1");
INSERT INTO `wold_country` VALUES ("72", "Fiji", "斐济", "FJ", "大洋洲", "679", "1");
INSERT INTO `wold_country` VALUES ("73", "Finland", "芬兰", "FI", "欧洲", "358", "1");
INSERT INTO `wold_country` VALUES ("74", "France", "法国", "FR", "欧洲", "33", "1");
INSERT INTO `wold_country` VALUES ("75", "France Metropolitan", "法国大都会", "FX", "", "33", "1");
INSERT INTO `wold_country` VALUES ("76", "French Guiana", "法属圭亚那", "GF", "南美洲", "594", "1");
INSERT INTO `wold_country` VALUES ("77", "French Polynesia", "法属玻里尼西亚", "PF", "", "689", "1");
INSERT INTO `wold_country` VALUES ("78", "French Southern Territories", "French Southern Territories", "TF", "", "", "0");
INSERT INTO `wold_country` VALUES ("79", "Gabon", "加蓬", "GA", "非洲", "241", "1");
INSERT INTO `wold_country` VALUES ("80", "Gambia", " 冈比亚", "GM", "非洲", "220", "0");
INSERT INTO `wold_country` VALUES ("81", "Georgia", "格鲁吉亚", "GE", "亚洲", "995", "1");
INSERT INTO `wold_country` VALUES ("82", "Germany", "德国", "DE", "欧洲", "49", "1");
INSERT INTO `wold_country` VALUES ("83", "Ghana", "加纳", "GH", "非洲", "233", "1");
INSERT INTO `wold_country` VALUES ("84", "Gibraltar", "直布罗陀", "GI", "欧洲", "350", "1");
INSERT INTO `wold_country` VALUES ("85", "Greece", "希腊", "GR", "欧洲", "30", "1");
INSERT INTO `wold_country` VALUES ("86", "Greenland", "格陵兰", "GL", "", "299", "1");
INSERT INTO `wold_country` VALUES ("87", "Grenada", "格林纳达", "GD", "北美洲", "1473", "1");
INSERT INTO `wold_country` VALUES ("88", "Guadeloupe", "瓜德罗普岛", "GP", "", "590", "1");
INSERT INTO `wold_country` VALUES ("89", "Guam", "关岛", "GU", "大洋洲", "1671", "1");
INSERT INTO `wold_country` VALUES ("90", "Guatemala", "危地马拉", "GT", "北美洲", "502", "1");
INSERT INTO `wold_country` VALUES ("91", "Guinea", "几内亚", "GN", "非洲", "224", "1");
INSERT INTO `wold_country` VALUES ("92", "Guinea-Bissau", "几内亚比绍", "GW", "", "245", "1");
INSERT INTO `wold_country` VALUES ("93", "Guyana", "圭亚那", "GY", "南美洲", "592", "1");
INSERT INTO `wold_country` VALUES ("94", "Haiti", "海地", "HT", "北美洲", "509", "1");
INSERT INTO `wold_country` VALUES ("95", "Heard and Mc Donald Islands", "Heard and Mc Donald Islands", "HM", "", "", "0");
INSERT INTO `wold_country` VALUES ("96", "Honduras", "洪都拉斯", "HN", "北美洲", "504", "1");
INSERT INTO `wold_country` VALUES ("97", "Hong Kong", "香港", "HK", "亚洲", "852", "1");
INSERT INTO `wold_country` VALUES ("98", "Hungary", "匈牙利", "HU", "欧洲", "36", "1");
INSERT INTO `wold_country` VALUES ("99", "Iceland", "冰岛", "IS", "欧洲", "354", "1");
INSERT INTO `wold_country` VALUES ("100", "India", "印度", "IN", "亚洲", "91", "1");
INSERT INTO `wold_country` VALUES ("101", "Indonesia", "印度尼西亚", "ID", "亚洲", "62", "1");
INSERT INTO `wold_country` VALUES ("102", "Iran (Islamic Republic of)", "Iran (Islamic Republic of)", "IR", "", "98", "0");
INSERT INTO `wold_country` VALUES ("103", "Iraq", "伊拉克", "IQ", "亚洲", "964", "1");
INSERT INTO `wold_country` VALUES ("104", "Ireland", "爱尔兰", "IE", "欧洲", "353", "1");
INSERT INTO `wold_country` VALUES ("105", "Isle of Man", "英国属地曼岛", "IM", "", "", "1");
INSERT INTO `wold_country` VALUES ("106", "Israel", "以色列", "IL", "亚洲", "972", "1");
INSERT INTO `wold_country` VALUES ("107", "Italy", "意大利", "IT", "欧洲", "39", "1");
INSERT INTO `wold_country` VALUES ("108", "Jamaica", "牙买加", "JM", "北美洲", "1876", "1");
INSERT INTO `wold_country` VALUES ("109", "Japan", "日本", "JP", "亚洲", "81", "1");
INSERT INTO `wold_country` VALUES ("110", "Jordan", "约旦", "JO", "亚洲", "962", "1");
INSERT INTO `wold_country` VALUES ("111", "Kazakhstan", "哈萨克", "KZ", "亚洲", "7", "1");
INSERT INTO `wold_country` VALUES ("112", "Kenya", "肯尼亚", "KE", "非洲", "254", "1");
INSERT INTO `wold_country` VALUES ("113", "Kiribati", "吉尔巴斯", "KI", "", "686", "1");
INSERT INTO `wold_country` VALUES ("114", "Kuwait", "科威特", "KW", "亚洲", "965", "1");
INSERT INTO `wold_country` VALUES ("115", "Kyrgyzstan", "吉尔吉斯", "KG", "亚洲", "996", "1");
INSERT INTO `wold_country` VALUES ("116", "Lao People's Democratic Republic", "老挝", "LA", "", "856", "11");
INSERT INTO `wold_country` VALUES ("117", "Latvia", "拉脱维亚", "LV", "欧洲", "371", "1");
INSERT INTO `wold_country` VALUES ("118", "Lebanon", "黎巴嫩", "LB", "亚洲", "961", "1");
INSERT INTO `wold_country` VALUES ("119", "Lesotho", "莱索托", "LS", "非洲", "266", "1");
INSERT INTO `wold_country` VALUES ("120", "Liberia", "利比里亚", "LR", "非洲", "231", "1");
INSERT INTO `wold_country` VALUES ("121", "Libyan Arab Jamahiriya", "利比亚", "LY", "非洲", "218", "1");
INSERT INTO `wold_country` VALUES ("122", "Liechtenstein", "列支敦士登", "LI", "欧洲", "423", "1");
INSERT INTO `wold_country` VALUES ("123", "Lithuania", "立陶宛", "LT", "欧洲", "370", "1");
INSERT INTO `wold_country` VALUES ("124", "Luxembourg", "卢森堡", "LU", "欧洲", "352", "1");
INSERT INTO `wold_country` VALUES ("125", "Macau", "澳门地区", "MO", "亚洲", "853", "1");
INSERT INTO `wold_country` VALUES ("126", "Madagascar", "马达加斯加", "MG", "非洲", "261", "1");
INSERT INTO `wold_country` VALUES ("127", "Malawi", "马拉维", "MW", "非洲", "265", "1");
INSERT INTO `wold_country` VALUES ("128", "Malaysia", "马来西亚", "MY", "亚洲", "60", "1");
INSERT INTO `wold_country` VALUES ("129", "Maldives", "马尔代夫", "MV", "亚洲", "960", "1");
INSERT INTO `wold_country` VALUES ("130", "Mali", "马里", "ML", "非洲", "223", "1");
INSERT INTO `wold_country` VALUES ("131", "Malta", "马尔他", "MT", "欧洲", "356", "1");
INSERT INTO `wold_country` VALUES ("132", "Marshall Islands", "马绍尔群岛", "MH", "大洋洲", "692", "1");
INSERT INTO `wold_country` VALUES ("133", "Martinique", "马提尼克岛", "MQ", "北美洲", "596", "1");
INSERT INTO `wold_country` VALUES ("134", "Mauritania", "毛里塔尼亚", "MR", "非洲", "222", "1");
INSERT INTO `wold_country` VALUES ("135", "Mauritius", "毛里求斯", "MU", "非洲", "230", "1");
INSERT INTO `wold_country` VALUES ("136", "Mayotte", "马约特", "YT", "", "269", "1");
INSERT INTO `wold_country` VALUES ("137", "Mexico", "墨西哥", "MX", "北美洲", "52", "1");
INSERT INTO `wold_country` VALUES ("138", "Micronesia", "密克罗尼西亚", "FM", "大洋洲", "691", "1");
INSERT INTO `wold_country` VALUES ("139", "Moldova", "摩尔多瓦", "MD", "欧洲", "373", "1");
INSERT INTO `wold_country` VALUES ("140", "Monaco", "摩纳哥", "MC", "欧洲", "377", "1");
INSERT INTO `wold_country` VALUES ("141", "Mongolia", "外蒙古", "MN", "亚洲", "976", "1");
INSERT INTO `wold_country` VALUES ("142", "Montenegro", "Montenegro", "MNE", "", "382", "0");
INSERT INTO `wold_country` VALUES ("143", "Montserrat", "蒙特色纳", "MS", "", "1664", "1");
INSERT INTO `wold_country` VALUES ("144", "Morocco", "摩洛哥", "MA", "非洲", "212", "1");
INSERT INTO `wold_country` VALUES ("145", "Mozambique", "莫桑比克", "MZ", "非洲", "258", "1");
INSERT INTO `wold_country` VALUES ("146", "Myanmar", "缅甸", "MM", "亚洲", "95", "1");
INSERT INTO `wold_country` VALUES ("147", "Namibia", "那米比亚", "NA", "非洲", "264", "1");
INSERT INTO `wold_country` VALUES ("148", "Nauru", "瑙鲁", "NR", "大洋洲", "674", "1");
INSERT INTO `wold_country` VALUES ("149", "Nepal", "尼泊尔", "NP", "亚洲", "977", "1");
INSERT INTO `wold_country` VALUES ("150", "Netherlands", "荷兰", "NL", "欧洲", "31", "1");
INSERT INTO `wold_country` VALUES ("151", "Netherlands Antilles", "荷兰安的列斯群岛", "AN", "", "599", "1");
INSERT INTO `wold_country` VALUES ("152", "New Caledonia", "新加勒多尼亚", "NC", "", "687", "1");
INSERT INTO `wold_country` VALUES ("153", "New Zealand", "新西兰", "NZ", "大洋洲", "64", "1");
INSERT INTO `wold_country` VALUES ("154", "Nicaragua", "尼加拉瓜", "NI", "北美洲", "505", "1");
INSERT INTO `wold_country` VALUES ("155", "Niger", "尼日尔", "NE", "非洲", "227", "1");
INSERT INTO `wold_country` VALUES ("156", "Nigeria", "尼日利亚", "NG", "非洲", "234", "1");
INSERT INTO `wold_country` VALUES ("157", "Niue", "纽鄂岛", "NU", "", "683", "1");
INSERT INTO `wold_country` VALUES ("158", "Norfolk Island", "诺福克岛", "NF", "", "672", "1");
INSERT INTO `wold_country` VALUES ("159", "North Korea", "朝鲜", "KP", "亚洲", "850", "1");
INSERT INTO `wold_country` VALUES ("160", "Northern Mariana Islands", "北马里亚纳群岛", "MP", "", "1670", "1");
INSERT INTO `wold_country` VALUES ("161", "Norway", "挪威", "NO", "欧洲", "47", "1");
INSERT INTO `wold_country` VALUES ("162", "Oman", "阿曼", "OM", "亚洲", "968", "1");
INSERT INTO `wold_country` VALUES ("163", "Pakistan", "巴基斯坦", "PK", "亚洲", "92", "1");
INSERT INTO `wold_country` VALUES ("164", "Palau", "帛琉", "PW", "", "680", "1");
INSERT INTO `wold_country` VALUES ("165", "Palestine", "巴勒斯坦", "PS", "亚洲", "970", "1");
INSERT INTO `wold_country` VALUES ("166", "Panama", "巴拿马", "PA", "北美洲", "507", "1");
INSERT INTO `wold_country` VALUES ("167", "Papua New Guinea", "巴布亚新几内亚", "PG", "大洋洲", "675", "1");
INSERT INTO `wold_country` VALUES ("168", "Paraguay", "巴拉圭", "PY", "南美洲", "595", "1");
INSERT INTO `wold_country` VALUES ("169", "Peru", "秘鲁", "PE", "南美洲", "51", "1");
INSERT INTO `wold_country` VALUES ("170", "Philippines", "菲律宾共和国", "PH", "亚洲", "63", "1");
INSERT INTO `wold_country` VALUES ("171", "Pitcairn", "皮特凯恩岛", "PN", "", "872", "1");
INSERT INTO `wold_country` VALUES ("172", "Poland", "波兰", "PL", "欧洲", "48", "1");
INSERT INTO `wold_country` VALUES ("173", "Portugal", "葡萄牙", "PT", "欧洲", "351", "1");
INSERT INTO `wold_country` VALUES ("174", "Puerto Rico", "波多黎各", "PR", "北美洲", "1787", "1");
INSERT INTO `wold_country` VALUES ("175", "Qatar", "卡塔尔", "QA", "亚洲", "974", "1");
INSERT INTO `wold_country` VALUES ("176", "Reunion", "Reunion", "RE", "", "262", "0");
INSERT INTO `wold_country` VALUES ("177", "Romania", "罗马尼亚", "RO", "欧洲", "40", "1");
INSERT INTO `wold_country` VALUES ("178", "Russian Federation", "俄罗斯联邦", "RU", "欧洲", "7", "1");
INSERT INTO `wold_country` VALUES ("179", "Rwanda", "卢旺达", "RW", "非洲", "250", "1");
INSERT INTO `wold_country` VALUES ("180", "Saint Kitts and Nevis", "圣吉斯和尼维斯", "KN", "", "1869", "1");
INSERT INTO `wold_country` VALUES ("181", "Saint Lucia", "圣卢西亚", "LC", "南美洲", "1758", "1");
INSERT INTO `wold_country` VALUES ("182", "Saint Vincent and the Grenadines", "圣文森和格林纳丁斯", "VC", "", "1784", "1");
INSERT INTO `wold_country` VALUES ("183", "Samoa", "美属萨摩亚", "WS", "大洋洲", "685", "1");
INSERT INTO `wold_country` VALUES ("184", "San Marino", "San Marino", "SM", "欧洲", "378", "0");
INSERT INTO `wold_country` VALUES ("185", "Sao Tome and Principe", "圣多美和普林西比", "ST", "非洲", "", "1");
INSERT INTO `wold_country` VALUES ("186", "Saudi Arabia", "沙特阿拉伯", "SA", "亚洲", "966", "1");
INSERT INTO `wold_country` VALUES ("187", "Senegal", "塞内加尔", "SN", "非洲", "221", "1");
INSERT INTO `wold_country` VALUES ("188", "Serbia", "塞尔维亚共和国", "RS", "欧洲", "381", "1");
INSERT INTO `wold_country` VALUES ("189", "Seychelles", "塞锡尔群岛", "SC", "非洲", "248", "1");
INSERT INTO `wold_country` VALUES ("190", "Sierra Leone", "塞拉利昂", "SL", "非洲", "232", "1");
INSERT INTO `wold_country` VALUES ("191", "Singapore", "新加坡", "SG", "亚洲", "65", "1");
INSERT INTO `wold_country` VALUES ("192", "Slovakia (Slovak Republic)", "斯洛伐克（斯洛伐克人的共和国）", "SK", "", "421", "1");
INSERT INTO `wold_country` VALUES ("193", "Slovenia", "斯洛文尼亚", "SI", "欧洲", "386", "1");
INSERT INTO `wold_country` VALUES ("194", "Solomon Islands", "索罗门群岛", "SB", "", "677", "1");
INSERT INTO `wold_country` VALUES ("195", "Somalia", "索马里", "SO", "非洲", "252", "1");
INSERT INTO `wold_country` VALUES ("196", "South Africa", "南非", "ZA", "非洲", "27", "1");
INSERT INTO `wold_country` VALUES ("197", "South Korea", "韩国", "KR", "亚洲", "82", "1");
INSERT INTO `wold_country` VALUES ("198", "Spain", "西班牙", "ES", "欧洲", "34", "1");
INSERT INTO `wold_country` VALUES ("199", "Sri Lanka", "斯里兰卡", "LK", "亚洲", "94", "1");
INSERT INTO `wold_country` VALUES ("200", "St. Helena", "圣海伦娜", "SH", "", "290", "1");
INSERT INTO `wold_country` VALUES ("201", "St. Pierre and Miquelon", "圣皮埃尔和密克罗", "PM", "", "508", "1");
INSERT INTO `wold_country` VALUES ("202", "Sudan", "苏丹", "SD", "非洲", "249", "1");
INSERT INTO `wold_country` VALUES ("203", "Suriname", "苏里南", "SR", "", "597", "1");
INSERT INTO `wold_country` VALUES ("204", "Svalbard and Jan Mayen Islands", "冷岸和央麦恩群岛", "SJ", "", "", "1");
INSERT INTO `wold_country` VALUES ("205", "Swaziland", "斯威士兰", "SZ", "非洲", "268", "1");
INSERT INTO `wold_country` VALUES ("206", "Sweden", "瑞典", "SE", "欧洲", "46", "1");
INSERT INTO `wold_country` VALUES ("207", "Switzerland", "瑞士", "CH", "欧洲", "41", "1");
INSERT INTO `wold_country` VALUES ("208", "Syrian Arab Republic", "叙利亚", "SY", "亚洲", "963", "1");
INSERT INTO `wold_country` VALUES ("209", "Taiwan", "台湾地区", "TW", "亚洲", "886", "1");
INSERT INTO `wold_country` VALUES ("210", "Tajikistan", "塔吉克", "TJ", "亚洲", "992", "1");
INSERT INTO `wold_country` VALUES ("211", "Tanzania", "坦桑尼亚", "TZ", "非洲", "255", "1");
INSERT INTO `wold_country` VALUES ("212", "Thailand", "泰国", "TH", "亚洲", "66", "1");
INSERT INTO `wold_country` VALUES ("213", "The former Yugoslav Republic of Macedonia", "前马其顿南斯拉夫共和国", "MK", "", "389", "1");
INSERT INTO `wold_country` VALUES ("214", "Togo", "多哥", "TG", "非洲", "228", "1");
INSERT INTO `wold_country` VALUES ("215", "Tokelau", "托克劳", "TK", "大洋洲", "690", "1");
INSERT INTO `wold_country` VALUES ("216", "Tonga", "汤加", "TO", "大洋洲", "676", "1");
INSERT INTO `wold_country` VALUES ("217", "Trinidad and Tobago", "千里达托贝哥共和国", "TT", "北美洲", "1868", "1");
INSERT INTO `wold_country` VALUES ("218", "Tunisia", "北非共和国", "TN", "非洲", "216", "1");
INSERT INTO `wold_country` VALUES ("219", "Turkey", "土耳其", "TR", "亚洲", "90", "1");
INSERT INTO `wold_country` VALUES ("220", "Turkmenistan", "土库曼", "TM", "亚洲", "993", "1");
INSERT INTO `wold_country` VALUES ("221", "Turks and Caicos Islands", "土克斯和开科斯群岛", "TC", "", "1649", "1");
INSERT INTO `wold_country` VALUES ("222", "Tuvalu", "图瓦卢", "TV", "", "688", "1");
INSERT INTO `wold_country` VALUES ("223", "Uganda", "乌干达", "UG", "非洲", "256", "1");
INSERT INTO `wold_country` VALUES ("224", "Ukraine", "乌克兰", "UA", "欧洲", "380", "1");
INSERT INTO `wold_country` VALUES ("225", "United Arab Emirates", "阿拉伯联合酋长国", "AE", "亚洲", "971", "1");
INSERT INTO `wold_country` VALUES ("226", "United Kingdom", "英国", "GB", "欧洲", "44", "1");
INSERT INTO `wold_country` VALUES ("227", "United States", "美国", "US", "北美洲", "1", "1");
INSERT INTO `wold_country` VALUES ("228", "United States Minor Outlying Islands", "美国小离岛", "UM", "", "", "1");
INSERT INTO `wold_country` VALUES ("229", "Uruguay", "乌拉圭", "UY", "南美洲", "598", "1");
INSERT INTO `wold_country` VALUES ("230", "Uzbekistan", "乌兹别克斯坦", "UZ", "亚洲", "998", "1");
INSERT INTO `wold_country` VALUES ("231", "Vanuatu", "瓦努阿图", "VU", "大洋洲", "678", "1");
INSERT INTO `wold_country` VALUES ("232", "Vatican City State (Holy See)", "梵蒂冈(罗马教廷)", "VA", "", "39", "1");
INSERT INTO `wold_country` VALUES ("233", "Venezuela", "委内瑞拉", "VE", "南美洲", "58", "1");
INSERT INTO `wold_country` VALUES ("234", "Vietnam", "越南", "VN", "亚洲", "84", "1");
INSERT INTO `wold_country` VALUES ("235", "Virgin Islands (British)", "维尔京群岛(英国)", "VG", "", "1284", "1");
INSERT INTO `wold_country` VALUES ("236", "Virgin Islands (U.S.)", "维尔京群岛(美国)", "VI", "", "1340", "1");
INSERT INTO `wold_country` VALUES ("237", "Wallis And Futuna Islands", "沃利斯和富图纳群岛", "WF", "", "681", "1");
INSERT INTO `wold_country` VALUES ("238", "Western Sahara", "西撒哈拉", "EH", "非洲", "685", "1");
INSERT INTO `wold_country` VALUES ("239", "Yemen", "也门", "YE", "亚洲", "967", "1");
INSERT INTO `wold_country` VALUES ("240", "Yugoslavia", "南斯拉夫", "YU", "", "381", "1");
INSERT INTO `wold_country` VALUES ("241", "Zambia", "赞比亚", "ZM", "非洲", "260", "1");
INSERT INTO `wold_country` VALUES ("242", "Zimbabwe", "津巴布韦", "ZW", "非洲", "263", "1");
